### ISSUE TITLE
这个adb我最后用 adb connect 127.0.0.1:7555 才连成功了

### ISSUE THREAD

**Issue by MrGuoRanDuo** [FirstJavaMaster/AzurLaneScripts#1]

**Comment by FirstJavaMaster** [comment]
估计你用的mumu模拟器吧。不同模拟器的端口不一致，ADB的实现细节也不同。也许 https://github.com/FirstJavaMaster/AzurLaneScripts/blob/master/README.md 有点帮助。

**Comment by MrGuoRanDuo** [comment]
是mumu    去找了下mumu的接口xd

**Comment by MrGuoRanDuo** [comment]
这个以后有什么发展方向啊  全功能吗

**Comment by FirstJavaMaster** [comment]
> 是mumu 去找了下mumu的接口xd

将来我将端口写成配置文件，可以省得打开命令行了

> 这个以后有什么发展方向啊 全功能吗

目前还是自己在用多一点，所以先做了最常用的刷关。接下来会尝试日常任务等内容

**Comment by FirstJavaMaster** [comment]
22c5cbde487f21dfa21440a5d7b083dee53c03f2 已修复
