### ISSUE TITLE
第一支队伍发现Boss后出现问题

### ISSUE THREAD

**Issue by fraelyfan** [FirstJavaMaster/AzurLaneScripts#11]
非常感谢你的脚本让我不用一直肝活动图，但是遇到Boss切换队伍后会浪费额外的油
遇敌逻辑写的是：第一支队伍发现Boss后，会尝试切换到第二支队伍，然后重新寻敌。待再次遇到Boss时便会发起进攻。
但是实际使用时在切换到第二支队伍后，遇到非Boss也会发起进攻。

**Comment by FirstJavaMaster** [comment]
是的. 这样做有一些其他考虑:
+ 切换到第二队伍后视角会变化, boss的图片可能切换到屏幕之外了
+ 平衡道中队和boss对的战斗次数, 不至于两个队伍的战斗经验获取差太多
+ 有时候boss的位置被非boss敌船或地形围住, 直接点击boss无法开启战斗

不过切换后boss还是拥有最高优先级, 只要视线内发现了boss还是会优先选择boss. 所以正常情况下切换队伍后不会浪费太多次数.

个人习惯, 省油的话还是用低耗队或者减员(每个队伍上4个或者更少). 不过现在懒得整理队伍我就一窝蜂全上了.
