### ISSUE TITLE
日服的话要怎么进行替换呢

### ISSUE THREAD

**Issue by OceanEyeFF** [FirstJavaMaster/AzurLaneScripts#12]
稍微换了一下识别的图片

然后cmd里面FightToEnd报错：
****
PS D:\脚本\BLHX\AzurLaneScripts> python3 .\FightToEnd.py
ADB PATH >>>> D:/脚本/BLHX/AzurLaneScripts/adb/adb.exe
检测设备连接状态 >>> emulator-5556 ...

设备列表：
emulator-5556   device

设备已连接

屏幕分辨率: Physical size: 1280x720
像素密度: Physical density: 240
系统类型: aosp
系统版本: 5.1.1

[单发模式] 如果已经在某个关卡中，则自动战斗至关卡结束

Traceback (most recent call last):
  File ".\FightToEnd.py", line 7, in <module>
    res = StageFight.wind_up_stage_fight()
  File "D:\脚本\BLHX\AzurLaneScripts\bin\StageFight.py", line 149, in wind_up_stage_fight
    if PageUtils.in_fight_page():
  File "D:\脚本\BLHX\AzurLaneScripts\common\PageUtils.py", line 69, in in_fight_page
    return AutoAdb().check('temp_images/page/in-fighting.png')
  File "D:\脚本\BLHX\AzurLaneScripts\common\AutoAdb.py", line 51, in check
    loc = self.get_location(*temp_rel_path_list, threshold=threshold)
  File "D:\脚本\BLHX\AzurLaneScripts\common\AutoAdb.py", line 39, in get_location
    res = cv2.matchTemplate(sp_gray, temp_gray, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'

****
这里的infighting图片已经进行了替换orz

**Comment by FirstJavaMaster** [comment]
是不是文件的名字写错了? in-fighting.png 路径和 名字都要保持一致

![image](https://user-images.githubusercontent.com/22362110/82789116-59fc1180-9e9c-11ea-9be2-19306696e84c.png)

**Comment by OceanEyeFF** [comment]
这个没写错orz

**Comment by OceanEyeFF** [comment]
我试了一下，好像路径名不能有中文

**Comment by OceanEyeFF** [comment]
然后活动图好像没有优化过qwq

**Comment by FirstJavaMaster** [comment]
> 然后活动图好像没有优化过qwq

是的，有些活动图敌人模板不太一样，可以手动往 temp_images\enemy 里加。
遇到那些有移动距离限制的图就不好用了，只能开着脚本手动点击移动和遇敌。脚本检测到进入战斗后会接管。
