### ISSUE TITLE
fight.py 无法开始战斗

### ISSUE THREAD

**Issue by bad7890** [FirstJavaMaster/AzurLaneScripts#13]
我是日服玩家, 不知道是不是因为这个造成一定的差别
一些按钮的模板我已经更换(出现问题的按钮模板我也已经更换),  fightToEnd.py可以正常完成所有战斗

目前的问题是:
  在活动关卡页面点击了目标关卡之后,  无法进入战斗地图.
原因: 
  在方法confirm_stage_team() 中, button_list里面的图片无法找到location导致一直没发生点击事件.
我在之前没有用过abd, 想问一下为什么我这个出击按钮他没办法找到呢? 作为一张合格的截图需要具备什么条件.

**Comment by FirstJavaMaster** [comment]
大概率是截图没有匹配到. 一般截图范围像下面这样. 如果能达到80%的匹配度就会认为"找到了".

![image](https://user-images.githubusercontent.com/22362110/82850454-0c7cb480-9f2f-11ea-9880-6d07df34b064.png)

观察一下那三个按钮是哪个没被认出来, 就重新截图替换一下模板. 截图范围可以适当缩小一点, 特征越明显越好

**Comment by Happiness-in-Danger** [comment]
![图片](https://user-images.githubusercontent.com/45912561/83357481-2db22a80-a39f-11ea-8435-d32bb0ace050.png)

我有时候会有这个问题
