### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by liyiliuxingyu** [FirstJavaMaster/AzurLaneScripts#4]
`❯ python .\Fight.py
ADB PATH >>>> C:\workspace\Code\Python\AzurLaneScripts/adb/adb.exe

检测设备 ...
设备已连接

屏幕分辨率: Physical size: 1080x2280
请将分辨率设置为 1280x720 (横向 平板模式)`

**Comment by FirstJavaMaster** [comment]
呃。。。请将分辨率设置为 1280x720 (横向 平板模式)`
