### ISSUE TITLE
关于设备连接的一点小建议

### ISSUE THREAD

**Issue by hgjazhgj** [FirstJavaMaster/AzurLaneScripts#5]
1. 现在我必须保证`adb devices`列表里至多有一个设备,但是我希望能够在有多个设备的情况下选取一个,或者直接选列表中的第一个   
这可能需要在很多地方增加一些参数,比如'adb'变为'adb -s ...',所以我提交了这个issue  
2. 尽管关卡的图片模板必须为720p下的截图,但是在运行时adb截图后套一层缩放就能不必限制手机分辨率了

另:您的代码有点复杂,我不敢乱改

**Comment by FirstJavaMaster** [comment]
现已支持多设备同时存在时操作ADB。配置文件中必须指定ADB连接地址。

截图缩放恐怕难以实现，图片对比是根据像素点来的，较高或较低分辨率缩放后像素点的信息可能不相同，难以保证80%的对比线（即80%的像素点是相同的）。此外图片的对比本身已经比较占用CPU资源了，部分场景下代码故意降低了对比频率以降低占用，图片缩放的话也会增加额外的负担。

**Comment by FirstJavaMaster** [comment]
如果有想法有能力可以尝试fork此项目自己做一些修改，如果合适会加入pr共同“造福人类”

**Comment by hgjazhgj** [comment]
图片的对比对系统资源的占用基本可以忽略不计了,因为adb的截图一张就得一秒,您还得写文件(autoadb.py第28行)  
我自己有个fgo的脚本项目,一开始我也担心处理图像对系统资源的消耗,但一会我就发现在设备io面前这都是小case.并且高消耗的缩放算法随便用也没关系,最后模板匹配结果也几乎不变,现在做下来识别15fps没问题  
代码是肯定要改的,只不过有点复杂,还在研究中

**Comment by FirstJavaMaster** [comment]
照目前的运行来看，主要的资源占用在模拟器截图这个操作上，我的cpu是i5-4590，执行截图命令时CPU占用会从20%~30%提升到30%~40%。截图文件的读写基本不占用磁盘。python程序占用在5%以下。不确定加入图片缩放后CPU占用和对比效果如何。等后面有时间我会试试看。“支持多分辨率”有了自然好，不过因为这个很容易“克服”，设置里改一下就好了，所以主要的精力会放在支持更多页面操作上，比如“刷活动图”，“解决移动格数限制”等

**Comment by hgjazhgj** [comment]
受教了,原来adb的截图不光慢的要命,还吃那么多cpu  
那就更应该用其他方式来截图了  
期待更多新功能上线

**Comment by projMiss** [comment]
https://github.com/Genymobile/scrcpy
这个项目截图很快

**Comment by hgjazhgj** [comment]
scrcpy是一个完整简洁高效的安卓投屏应用，我一直用的是这个软件。它比百度上搜出来那些杂七杂八的付费投屏应用是高到不知道哪里去了。
但是他没有提供任何获取截图的接口啊。至少python是没法访问他的。

**Comment by hgjazhgj** [comment]
我自己的项目里用的是airtest中未公开的接口，效率还说得过去。大概10fps

**Comment by projMiss** [comment]
我是再用win32api截它窗口图

**Comment by hgjazhgj** [comment]
以前我也是这么干的，但是到最后代码又臭又长，根本难以维护。

**Comment by projMiss** [comment]
嘛，截图能用就行，反正难点在图像识别那边
