### ISSUE TITLE
刷9-2的图出现的问题

### ISSUE THREAD

**Issue by aimerya9** [FirstJavaMaster/AzurLaneScripts#6]
清过几次地图上的怪以后会搜索怪，然后就会一直移动地图，然后就一直移动

**Comment by FirstJavaMaster** [comment]
一直移动地图一般有以下原因：

+ 敌人的截图没有在模板列表里
+ 最后一个敌人被自己挡住了，看不见（将来脚本会自动处理这种情况）
+ 极小的概率会出现本应当识别的敌人没有被识别，重启后就好了，这种情况需要排查
