### ISSUE TITLE
寻找目标关卡问题

### ISSUE THREAD

**Issue by Happiness-in-Danger** [FirstJavaMaster/AzurLaneScripts#7]
总是一直在寻找目标关卡，
![QQ截图20200415192400](https://user-images.githubusercontent.com/45912561/79332073-c820f080-7f4e-11ea-8fba-50b47ad5e40c.png)

**Comment by FirstJavaMaster** [comment]
参考 https://github.com/FirstJavaMaster/AzurLaneScripts#运行 这部分说明，如果还不行的话可能模板截取得不太好，没检测出来。重新截取想要战斗的关卡截图

**Comment by Happiness-in-Danger** [comment]
@FirstJavaMaster 不行，只能点进某个关卡，可以自动战斗。下一个循环还是在扫描目标关卡。

**Comment by FirstJavaMaster** [comment]
寻找关卡的逻辑很简单，就是从 `temp_images/target-stage` 文件夹内拿到所有的模板去匹配当前的游戏界面。确认以下几点：

+  `temp_images/target-stage` 文件夹内已经放入了自己想要的关卡截图
+ 脚本开始执行时，**游戏界面已经处在“出击”界面**，例如：https://github.com/FirstJavaMaster/AzurLaneScripts/raw/master/wiki/unit.png
+ 自己想要进入的关卡就在当前“出击”界面内。比如我想去4-4关卡，但是出击界面在5-1 ~ 5~4单元内是不行的
+ 脚本是最新的

**Comment by FirstJavaMaster** [comment]
寻找关卡的逻辑很简单，就是从 `temp_images/target-stage` 文件夹内拿到所有的模板去匹配当前的游戏界面。确认以下几点：

+  `temp_images/target-stage` 文件夹内已经放入了自己想要的关卡截图
+ 脚本开始执行时，**游戏界面已经处在“出击”界面**，例如：https://github.com/FirstJavaMaster/AzurLaneScripts/raw/master/wiki/unit.png
+ 自己想要进入的关卡就在当前“出击”界面内。比如我想去4-4关卡，但是出击界面在5-1 ~ 5~4单元内是不行的
+ 脚本是最新的

**Comment by Happiness-in-Danger** [comment]
![图片](https://user-images.githubusercontent.com/45912561/79336845-07ebd600-7f57-11ea-90fb-b86a8a847070.png)
这是我的模板。
出击界面在那一章节的界面。

**Comment by FirstJavaMaster** [comment]
试试只截取“3-4 最后的”这部分。再往右的话是透明的，而背景是动态的，所以可能重合度达不到80%

**Comment by Happiness-in-Danger** [comment]
好了，谢谢！

**Comment by Happiness-in-Danger** [comment]
![Uploading 图片.png…]()
发现一个问题。

**Comment by Happiness-in-Danger** [comment]
![图片](https://user-images.githubusercontent.com/45912561/79351516-586d2e80-7f6b-11ea-9a9b-4a3d07463fa5.png)
发现一个问题。打着打着就跑到演习界面了

**Comment by FirstJavaMaster** [comment]
> ![图片](https://user-images.githubusercontent.com/45912561/79351516-586d2e80-7f6b-11ea-9a9b-4a3d07463fa5.png)
> 发现一个问题。打着打着就跑到演习界面了

是有可能发生这个问题：战斗结束后要判断成功/失败时不同的界面显示，有时候点击太快了就会点到结束后的“演习”按钮，今天维护结束后我再优化一下这里的判断逻辑

**Comment by Happiness-in-Danger** [comment]
我有一个小小的建议，在开始匹配关卡的是时候。可以加上坐标，模板太难取了。如果可以通过给定坐标进行重复战斗那就好了。希望考虑一下。谢谢！

**Comment by Happiness-in-Danger** [comment]
我有一个小小的建议，在开始匹配关卡的是时候。可以加上坐标，模板太难取了。如果可以通过给定坐标进行重复战斗那就好了。希望考虑一下。谢谢！

**Comment by FirstJavaMaster** [comment]
> 我有一个小小的建议，在开始匹配关卡的是时候。可以加上坐标，模板太难取了。如果可以通过给定坐标进行重复战斗那就好了。希望考虑一下。谢谢！

模板用QQ截图之类的还是挺方便的吧。一般关卡文字截一半，匹配成功率接近100%。

使用模板的好处就是可以保存多个关卡的模板。特殊关卡，困难关卡一次保存往后可以一直使用，否则普通关卡跑完了要跑困难关卡的话还要来回修改坐标。你觉得呢？

**Comment by Happiness-in-Danger** [comment]
应该是我截图技术问题，我有的关卡怎么截图都没有啥用。尤其是第六章。毕竟我是拿这个来捞船。
