### ISSUE TITLE
卡在演习界面

### ISSUE THREAD

**Issue by SUISHUI** [FirstJavaMaster/AzurLaneScripts#9]
刷3-4时，卡在演习界面，不停显示   “滑动页面。 累积次数   ”

**Comment by FirstJavaMaster** [comment]
战斗结束后可能会多点一下，就卡在演习界面了。现在已经处理了这种情况

**Comment by FirstJavaMaster** [comment]
52ac0e7e4116da88ca74eb418afa72ec51bba8da
update again
